open-craft/openedx-completion-aggregator

- completion_aggregator/apps.py
- completion_aggregator/signals.py
- requirements/test.in
- requirements/test.txt
- setup.cfg
- test_settings.py
- test_utils/test_app/apps.py
- tests/test_signals.py
**Description:** This connects the completion_aggregator app to the signal fired when a BlockCompletion gets saved.  A follow-up PR (#4) will implement responding to that signal to update Aggregators for the course.  For now, it just logs that the update happened.
**JIRA:** MCKIN-5902, OC-3097
**Dependencies:** Depends on aggregator model PR, #1, currently waiting on upstream review.
**Testing instructions:** 
1. Run the test suite, and see that tests pass.
2. Configure logging to display DEBUG level logs.
3. Install into a current version of edx-platform. (pip install the repo, at this branch and update the INSTALLED_APPS in lms/envs/common.py)
4. Enable the completion waffle switch. (completion.enable_completion_tracking)
5. Work through a course to create new …
> Create signal handler to respond when BlockCompletions are updated 

- README.rst
- completion_aggregator/__init__.py
- completion_aggregator/apps.py
- completion_aggregator/settings/aws.py
- completion_aggregator/settings/common.py
- requirements/dev.txt
- requirements/doc.txt
- requirements/test.txt
- setup.py
**Description:** edx-platform has recently added a pattern for including code as a "plugin" (without needing to add configuration to edx-platform).  This makes completion-aggregator follow that pattern.
**JIRA:** OC-3969
**Dependencies:** Waiting on #1 to land.
**Installation instructions:** Make sure there is no existing version of openedx-completion-aggregator installed (via `pip freeze`), then pip install this branch into a devstack running a recent commit on the master branch of edx-platform.
After installing per the instructions above:
1. Run `./manage.py lms --settings=devstack_docker shell`
2. Verify that `completion_aggregator.apps.CompletionAggregatorAppConfig` was added to `django.conf.settings.INSTALLED_APPS`.
3. Verify that …
> Convert completion-aggregator to pluggable django app.

- AUTHORS
- completion_aggregator/api/v1/views.py
- completion_aggregator/compat.py
- completion_aggregator/serializers.py
- completion_aggregator/signals.py
- test_utils/compat.py
- test_utils/test_app/models.py
- tests/test_views.py
**Description:** Alters the existing Completion Course Detail View to allow staff users to retrieve all aggregators for all enrolled users in a given course.
**JIRA:** MCKIN-7342, OC-4370
* In Studio, create 2 courses (e.g. Course A, Course B) with completable units.
* Enroll 2 learners in both courses (e.g. `honor`, `verified`)
* As the first learner, complete several units of Course A and Course B.
* As the second learner, complete units only in Course A.
* As a learner, check the Completion Aggregator API for each course to ensure that you can see only that learner's aggregations using the various URLs.
Can add `?requested_fields=user` to see the username.
* list all courses: `<lms_url>/completion-aggregator/v1/course/`
* course detail: …
> [MCKIN-7324] Provide API endpoint to fetch aggregators for all enrolled users in a course

- completion_aggregator/compat.py
- completion_aggregator/settings/common.py
- completion_aggregator/tasks.py
- completion_aggregator/transformers.py
- setup.py
- test_utils/compat.py
- tests/test_signals.py
- tests/test_tasks.py
- tests/test_views.py
**Description:**
This limits completion aggregation to relevant subgraphs of a course, by adding a block structure transformer that annotates completable blocks with the aggregator blocks that contain them.
**JIRA:** OC-3967
I created a two-section course, each section containing one unit with an HTML component and an input problem. This makes it reasonably easy to monitor the completion aggregation.
These changes should result in no noticeable alteration to the end result of completion aggregation, but in the logs, you should see that only the aggregator blocks containing the blocks you complete are updated.
**Reviewers:**
finished.
**Author concerns:** 
This has lots of debugging logging that should be removed.
> Calculate completion only for relevant sub-graphs of a course

- completion_aggregator/api/common.py
- completion_aggregator/api/v0/urls.py
- completion_aggregator/api/v0/views.py
- completion_aggregator/api/v1/views.py
- completion_aggregator/compat.py
- completion_aggregator/serializers.py
- completion_aggregator/urls.py
- test_utils/compat.py
- tests/test_views.py
**Description:** Rewire completion v0 api to use completion-aggregator infrastructure
**JIRA:** OC-4522
**Dependencies:**  OC-4528
instructions.
Check output of: /api/completion-aggregator/v0/course/
And compare to: /api/completion/v0/course/
Check output of: /api/completion/v0/course/course-course-v1:edX+DemoX+Demo_Course/
And compare to: /api/completion-aggregator/v0/course/course-v1:edX+DemoX+Demo_Course/
**Reviewers:**
- @jcdyer 
finished.
**Author concerns:** Missing migration of [CompletionBlockUpdateView](https://github.com/edx-solutions/edx-platform/blob/master/lms/djangoapps/completion_api/views.py#L441). @jcdyer shouldn't this …
> Rewire completion v0 api to use completion-aggregator infrastructure

- README.rst
- completion_aggregator/api/v0/views.py
- completion_aggregator/api/v1/views.py
- completion_aggregator/models.py
- completion_aggregator/serializers.py
- tests/test_serializers.py
- tests/test_views.py
**Description:** Describe in a couple of sentence what this PR adds
**JIRA:** MCKIN-7831, OC-4787
**Dependencies:** None
**Installation instructions:** None
1. Ensure the `completion.enable_completion_tracking` waffle switch is enabled in the lms, and 
`settings.COMPLETION_AGGREGATOR_ASYNC_AGGREGATION = True`.
1. Create some BlockCompletions, either by browsing a course, or from a `./manage.py lms shell`
1. Verify (from the logging or from the command line) that `StaleCompletions` are being created (but not resolved), and the corresponding `Aggregator` objects are not created/updated.
1. Using a staff account, hit the multi-user API endpoint, and verify (from the logging or from the command line) that:
1. `StaleCompletions` are not being …
> [MCKIN-7831] Make single-user aggregator endpoint calculate on the fly

- completion_aggregator/management/commands/migrate_progress.py
- completion_aggregator/tasks/aggregation_tasks.py
**Description:** Provides a management command to create BlockCompletions for every CourseModuleCompletion object in the progress app.
**JIRA:** OC-4528
**Merge deadline:** N/A
**Installation instructions:** In a ginkgo devstack on the development branch, uninstall openedx-completion-aggregator, and reinstall it from this branch.
**Testing instructions:**  
1. Check that there are progress_coursemodulecompletion objects in your database.  If not, browse through a few course sections.
2. Remove all BlockCompletion and Aggregator objects, so you have a couple dozen
3. Run ./manage.py lms --settings=devstack migrate_progress --batch-size=10 --verbosity=2
4. Confirm that Batches are processed, and that BlockCompletions and Aggregators are created.
**Reviewers:**
**Merge …
> Add command to convert progress models to BlockCompletions.

- Makefile
- completion_aggregator/__init__.py
- requirements/dev.txt
- requirements/doc.txt
- requirements/quality.txt
- requirements/test.in
- requirements/test.txt
- requirements/travis.txt
- setup.py
* Move pytest-django from setup.py to requirements files.  This fixes a problem running tests in edx-platform.
* Upgrade requirements.
* Bump aggregator version to 1.1
**JIRA:** [OC-4767](https://tasks.opencraft.com/browse/OC-4767)
**Merge deadline:** List merge deadline (if any)
instructions.
1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happend instead - check failed.
**Reviewers:**
finished.
**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.
> Remove pytest-django from install_requires

- completion_aggregator/models.py
- completion_aggregator/tasks/aggregation_tasks.py
- completion_aggregator/utils.py
- tests/test_aggregation_tasks.py
- tests/test_models.py
- tests/test_util_functions.py
This PR adds support to reduce the number of queries made to insert aggregation data per course. It uses Mysql Insert on Duplicate Update query, so that a single query can be sent which contains manyu rows of aggregation data
**JIRA:** [OC-4844](https://tasks.opencraft.com/browse/OC-4844)
**Dependencies:** NA
**Merge deadline:** List merge deadline (if any)
instructions.
Tests should pass
**Reviewers:**
finished.
**Author concerns:** 
* Functions like `AggregatorManager.validate` and the logic to calculate percentage completion are duplicated in `AggregationUpdater._is_aggregator_data_valid` and `utils.get_percent`. I was not sure where to keep …
> Use mysql on insert duplicate update query to reduce number of aggregation query per course.

- completion_aggregator/compat.py
- completion_aggregator/tasks/aggregation_tasks.py
- test_utils/compat.py
- tests/test_aggregation_tasks.py
- tox.ini
Some courses no longer exist, and some have bad modulestore data that raises TypeErrors (in course blocks parsing).
**Description:** This handles errors gracefully when trying to load and parse modulestore data.  In those cases, we log a warning, and abort gracefully.
**JIRA:** [OC-5174](https://tasks.opencraft.com/browse/OC-5174)
**Dependencies:** 
**Merge deadline:** ASAP.  This is needed for completion rollout.
**Installation instructions:** List any non-trivial installation Link to JIRA ticket
instructions.
1. Create a stale completion for a course that doesn't exist.
2. Run completions.
3. Verify that an error gets logged, but the task doesn't crash.
**Reviewers:**
finished.
**Author concerns:** N/A
> Handle aggregation for courses with bad data

- completion_aggregator/__init__.py
- completion_aggregator/serializers.py
- tests/test_serializers.py
- tests/test_views.py
**Description:** Return 0 instead of None if the learner has no aggregators.
**JIRA:** [MCKIN-8468](https://edx-wiki.atlassian.net/browse/MCKIN-8468), [BEBOP-316](https://tasks.opencraft.com/browse/BEBOP-316)
**Dependencies:** None
1. Enroll a user in a course.  
2. DO NOT VISIT THE COURSE
3. Request completions for the user.
4. See value returned as 0.0.
5. Verify that apros doesn't error as described in the ticket.
**Reviewers:**
finished.
**Author concerns:** None
> Update unviewed aggregators to return 0 percent completion.

- completion_aggregator/compat.py
- completion_aggregator/serializers.py
- completion_aggregator/tasks/aggregation_tasks.py
- requirements/dev.txt
- requirements/doc.txt
- requirements/test.txt
- tests/test_serializers.py
- tests/test_views.py
**Description:** Maintain recalculation of stale blocks on single-user views, but do not save to db.  Resolves some db locking issues.
**JIRA:** [MCKIN-8483](https://edx-wiki.atlassian.net/browse/MCKIN-8483) [BB-330](https://tasks.opencraft.com/browse/BB-330)
**Reviewers:**
finished.
**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.
> Recalculate serializers without saving to database.

- completion_aggregator/__init__.py
- completion_aggregator/serializers.py
- tests/test_serializers.py
Fixes error that occurs when you ask for mean value in a course without any Aggregators. 
**Reviewers:**
finished.
> Fix error when getting means for course without aggregators

- completion_aggregator/__init__.py
- completion_aggregator/serializers.py
- completion_aggregator/tasks/aggregation_tasks.py
- test_settings.py
- test_utils/test_blocks.py
- tests/test_aggregation_tasks.py
- tests/test_serializers.py
- tests/test_views.py
**Description:** When live-calculating aggregators, the percent field was not getting populated.  Populate it.
**JIRA:** 
Fixes:
* MCKIN-8474
* BB-365
Affects:
* MCKIN-8099
**Dependencies:** N/A 
**Installation instructions:** Usual completion flags, included COMPLETION_AGGREGATOR_ASYNC_AGGREGATION = True
1. Complete some blocks.
2. Load single-course completion api for one user.  
3. See that percent is 0.0, even when earned is not 0.0.
4. install this branch.
5. Repeat step 2.
6. See that percent > 0.0 when earned > 0.0.
**Reviewers:**
finished.
**Author concerns:**
> Ensure new percent is included in live-updated aggregators.

- completion_aggregator/api/common.py
- completion_aggregator/api/v1/views.py
- tests/test_views.py
**Description:** Changed the behavior to give a 403 error when a non-staff users tries to request data about all/another user. Updated the tests to reflect this change. 
**JIRA:** https://tasks.opencraft.com/browse/BB-370
**Dependencies:** -
**Merge deadline:** -
**Installation instructions:** -
Use something like postman to call the API.
**Reviewers:**
- None selected yet
finished.
**Author concerns:**  Do we need to add a Changelog for this?
> [BB-370] Non staff users now get 403 error when trying to request aggregator data about other users

- completion_aggregator/__init__.py
- completion_aggregator/aggregator.py
- setup.py
- tests/test_aggregator.py
**Description:** Current behavior is to aggregate oldest stale completions first, but this means we have to wait a long time before seeing the most recent activity, while getting historical data right away.  That could delay testing.
**JIRA:** YONK-1089
**Merge deadline:** ASAP.
**Installation instructions:** N/A
1.  Install this branch of openedx-completion-aggregator into any version of edx-platform (solutions is ideal, but it works on 
2.  Create a number of BlockCompletions, more than 5, in two different courses, by browsing through several pages of the courses.  
Ways to complete blocks:
* Spend at least five seconds on each page, scroll all the way to the bottom of the page.
* Watch the last 5-10 seconds of a video.
* Submit answers to …
> Aggregate recent StaleCompletions first.

- completion_aggregator/__init__.py
- completion_aggregator/api/v0/views.py
- tests/test_views.py
**Description:** We recently added the requirement to specify a username for non-staff users requesting their own information.  This breaks existing mobile apps using the v0 api.  Here we revert the behavior for the v0 api, but maintain it for v1.
**JIRA:** https://edx-wiki.atlassian.net/browse/MCKIN-8690
**Dependencies:** N/A 
**Merge deadline:** N/A
**Testing instructions:**  Verify that accessing v0 completion apis without specifying a username returns data for the logged in user, if non-staff.
**Reviewers:**
finished.
**Author concerns:** None.
> MCKIN-8690: Allow non-staff queries without explicit username in v0 api.

- completion_aggregator/__init__.py
- completion_aggregator/migrations/0004_index_stalecompletion.py
**Description:** Make the stalecompletion index migration succeed if it encounters an empty table.  If a previous migration failed partway through, completion_aggregator_stalecompletionnew might exist, so delete that if it does.
**JIRA:** BB-85.
instructions.
1. Have an empty table.
2. Manually create a completion_aggregator_stalecompletionnew table if it doesn't exist.
3. Run the migration.
4. Verify that the migration succeeds.  Verify that the table has indexes added to it.
**Reviewers:**
finished.
**Author concerns:** List any concerns about this PR - inelegant …
> Make migration resilient to having an empty table.

- completion_aggregator/__init__.py
- completion_aggregator/api/v0/urls.py
- completion_aggregator/api/v0/views.py
- completion_aggregator/compat.py
- test_utils/test_app/models.py
- tests/test_views.py
**Description:** This endpoint existed on the old version of the v0 api, and somehow didn't get ported to the new, blockcompletion based v0.  This ticket updates that, and fixes a major blocker for deploying completion.
**JIRA:** MCKIN-8766, BB-493
**Merge deadline:** ASAP.
As an authenticated user, submit a post to the specified endpoint with a valid course key and block key in that course, and a body of 
```json
{"completion": 1.0}
```
Verify that a BlockCompletion object gets created for the logged-in user.
**Reviewers:**
finished.
**Author concerns:** N/A
> MCKIN-8766: Restore the missing block-update endpoint to the v0 api.

- completion_aggregator/__init__.py
- completion_aggregator/api/v1/views.py
- completion_aggregator/management/commands/reaggregate_course.py
- completion_aggregator/serializers.py
- completion_aggregator/tasks/aggregation_tasks.py
- test_utils/compat.py
- tests/test_views.py
**Description:** Adds the ability to specify a block key to serve as the root of the requested aggregators.  If the view would calculate them on the fly, it instead only calculates the aggregators under (and including) the specified block.  
Some notes: 
* if it doesn't calculate the aggregators, it ignores the root_block parameter, and sends back all the data, because it would take more time to calculate which ones need to be returned than just to make the single indexed db query to get the blocks.  
* One point of ugliness is that the course-level aggregator gets returned as `0.0/None/0.0`  I don't see an easy way to resolve that, given the format of the response, but since the user only wanted a subtree anyway, we'll expect them not to use that data.
**JIRA:** …
> Add root_block option to only get a subtree of aggregators

- completion_aggregator/__init__.py
- completion_aggregator/management/commands/migrate_progress.py
- completion_aggregator/tasks/aggregation_tasks.py
Update the migrate_progress command with a few new enhancements:
* Add an option to copy CoureModuleCompletion objects by id.
* Migrate batches by id, rather than by offset.
* Add a `select_related` clause to prevent pulling user objects separately.
**JIRA:** MCKIN-8829
instructions.
*    Using manage.py dbshell, Check that you have some entries in progress_coursemodulecompletions (CMC). Check a few id values.
*    Delete all your completion_blockcompletion records.
*    Run ./manage.py lms --settings=devstack migrate_progress --ids=1,4,5,10,8 with a few IDs that are present in your CMC table, and a few that are not.
*    Verify that …
> Allow migrating specific coursemodulecompletions by id.

- Makefile
- completion_aggregator/api/v0/urls.py
- completion_aggregator/api/v1/urls.py
- completion_aggregator/models.py
- completion_aggregator/tasks/aggregation_tasks.py
- tests/test_aggregation_tasks.py
- tests/test_aggregator.py
- tests/test_signals.py
- tests/test_views.py
When updating aggregators, sometimes a StaleCompletion exists for a User that doesn't exist (probably from old data or test data that sneaked in).  Those cause harmless errors, but the errors mean that the StaleCompletion doesn't get resolved, so the same errors occur every hour.  This PR resolves the StaleCompletions.
**JIRA:** [BB-524](https://tasks.opencraft.com/browse/BB-524)
instructions.
1. Create a stale completion for a non-existent user.
2. Run `./manage.py run_aggregator_service`
3. Verify that the StaleCompletion is marked resolved, and that no exceptions are raised.
Note, …
> BB-524: Handle stale completions for unknown users.

- tests/test_views.py
**Description:** Adds a test for specifying user_ids in API requests functionality
**JIRA:** https://tasks.opencraft.com/browse/BB-533
**Dependencies:** 
**Merge deadline:**
Run the test at 
`openedx-completion-aggregator/tests/test_views.py::CompletionViewTestCase::test_detail_view_staff_requested_multiple_users`
**Reviewers:**
finished.
**Author concerns:**
I'm having troubles installing dependencies on Ubuntu 18.04 in order to run the tests. Needs to be confirmed working before merge.
> [BB-533] Create test for specifying user_ids in API request

- completion_aggregator/__init__.py
- completion_aggregator/core.py
- completion_aggregator/management/commands/run_aggregator_service.py
- tests/test_core.py
**Description:** Previously, the hourly aggregation task was failing whenever it encountered a course with an invalid block type.  This happened with historical courses that had run when different blocks were available.  Apparently at some time in the past, `image-explorer` was called `image_explorer`, and now any courses that contain an `image_explorer` block fail to aggregate completions, and the `StaleCompletion` records never get cleared out.  As a result, it tries to aggregate the same course every hour, and our client sees a few otherwise harmless errors in their NewRelic reporting.
This change should allow some of those records to be cleared out, and silence the errors.
**JIRA:** MCKIN-9209, BB-759
On a …
> MCKIN-9202: Exclude unregistered block types from completion.

- completion_aggregator/__init__.py
- completion_aggregator/cachegroup.py
- completion_aggregator/compat.py
- completion_aggregator/core.py
- test_utils/compat.py
- tests/test_batch.py
- tests/test_core.py
**Description:** Reduce memory footprint of cache entries.
We do this by extracting only the information we need from the BlockStructure
object and storing it in simple data structures.
Also included:
* Removing redundant db queries.
* Only setting cache values when new values have been calculated (otherwise, just bump the timeout)
**JIRA:** YONK-1302, [BB-820](https://tasks.opencraft.com/browse/BB-820)
This is a performance refactor.  Verify that views that depend on completions still get accurate results, and that the size of cache entries is reduced by this operation.  
After visiting course pages in apros, check the size of the …
> YONK-1302: Reduce memory footprint of cache entries.

- completion_aggregator/__init__.py
- completion_aggregator/core.py
- test_utils/compat.py
- tests/test_core.py
We recalculate the entire course when they are found, so we know that
our aggregators reflect the current structure of the course.  This
should be a relatively rare occurrence.
This PR also fixes an issue where block aggregators were not being found
in the test compat library.  This made every test run act as though all
aggregators had been changed.
Finally, we add a test to cover the case where a block has been
completed but the block key is not included in the list of
changed_blocks, and so the aggregator is not updated.  A later run of the
aggregator will catch the new change.
**JIRA:** BB-941 - Need to find or create a MCKIN/YONK ticket.
**Dependencies:** N/A 
See new test cases.  Manual testing would …
> BB-941: Handle missing block keys gracefully.

- completion_aggregator/__init__.py
- completion_aggregator/batch.py
- completion_aggregator/core.py
- test_utils/compat.py
- tests/test_batch.py
- tests/test_serializers.py
**Description:** There are a large number of StaleCompletions on stage that are not getting resolved properly.  They all seem to be for non existent courses, and all have a block_key of `''`.  Make sure those conditions are accounted for when resolving completions.
**JIRA:** [MCKIN-10256](https://edx-wiki.atlassian.net/browse/MCKIN-10256)
**Merge deadline:** N/A
instructions.
See newly added unit tests.  
1. Create a stale completion with a course_key of `'non/existent/block'` and a block_key of `''`.  
2. On the main branch, run ./manage.py lms --settings=devstack run_aggregator_service, and confirm that the block is not …
> MCKIN-10256: Resolve stale completions that contain a course_key to a nonexistent course

- completion_aggregator/__init__.py
- setup.py
**Description:**
We are currently using openedx-completion-aggregator==1.5.23 fro ginkgo release and this version is deployed on prod. This version of openedx-completion-aggregator is using edx-completion==1.0.3 but ironwood release of edx-platform is using edx-completion==2.0.0
It seems like that completion-aggregator is using an older version of edx-completion. The version is pinned here.
As we are rebasing to ironwood release so we should look into completion-aggregator to find out if we can upgrade the dependant version of edx-completion to make it compatible with ironwood. 
**JIRA:** https://openedx.atlassian.net/browse/YONK-1515
**Merge deadline:** Early next sprint
1. install openedx-completion-aggregator
2. Check if progress updating for courses. …
> YONK-1515 Updated edx-completion max version to 2.0.0

- CHANGELOG.rst
- completion_aggregator/__init__.py
- completion_aggregator/signals.py
- completion_aggregator/tasks/handler_tasks.py
**Description:** Prevents issues when signal handlers receive CourseLocators instead of string, as these are passed to Celery tasks and fail JSON serialisation.
**JIRA:** BB-2271
**Testing instructions:** Check related PR
**Reviewers:**
finished.
**Author concerns:** None
> [BB-2271] Convert course_key to string for mark_all_stale.delay

- CHANGELOG.rst
- completion_aggregator/__init__.py
- completion_aggregator/management/commands/reaggregate_course.py
- completion_aggregator/tasks/handler_tasks.py
**Description:** This fixes running aggregator for all courses by disabling the `CourseKey.from_string` casting for non-string objects.
**JIRA:** [BB-2296](https://tasks.opencraft.com/browse/BB-2296)
**Merge deadline:** as soon as possible
1. Install aggregator from this branch.
1. Run aggregator for all courses `/edx/bin/manage.edxapp lms reaggregate_course -a`. It should not break.
1. (Optionally) run aggregator for demo course: `/edx/bin/manage.edxapp lms reaggregate_course -c course-v1:edX+DemoX+Demo_Course`.
**Reviewers:**
finished.
> [BB-2296] Fix course conversion in `reaggregate_course` management command

- completion_aggregator/__init__.py
- completion_aggregator/api/v0/views.py
**Description:** In Juniper [completion submission](https://github.com/edx/completion/blob/3.2.0/completion/models.py#L91..L96) (edx-completion==3.2.0) expects Old mongo 
block keys to be annotated with course run info before other wise it throws exception linked above. This PR adds course info in completion api before submission.
**JIRA:** https://edx-wiki.atlassian.net/browse/MCKIN-29363
**Dependencies:** None. 
1. Create a course using old mongo(DraftModuleStore)
2. Add html block to the course
3. Do post request to the API `http://edx.devstack.lms:18000/api/completion/v0/<course_id>/blocks/<old mongo block id>/`
4. Server will respond with 500.
5. After applying above fix it should not through exception and update the progress. …
> fix completion submission for old mongo keys

- completion_aggregator/__init__.py
- completion_aggregator/utils.py
- tests/test_util_functions.py
**Description:** Fixes the Django version check for timezones.
1. Create a virtualenv and install the test requirements.
2. Install "Django>=2" inside the virtualenv.
3. Using a shell, call the [make_datetime_timezone_unaware](https://github.com/open-craft/openedx-completion-aggregator/blob/master/completion_aggregator/utils.py#L40) function with a date and confirm the resulting date is timezone-unaware.
Optional: Repeat steps 2-3 using other Django versions built after [this commit](https://github.com/django/django/commit/e707e4c709c2e3f2dad69643eb838f87491891f8#diff-af003fcfed7cfbdeb396f8647ed0f92fR258).
**Reviewers:**
finished.
> Fix Django version check

- completion_aggregator/__init__.py
- completion_aggregator/core.py
**Description:** Modified date for Aggregator is being set incorrectly(in the past). The issue is happening because in Juniper release model_utils have been upgraded to version 4.0.0 from version 3.0.0 in ironwood. This new version adds [this method](https://github.com/jazzband/django-model-utils/blob/4.0.0/model_utils/fields.py#L32) which populates the modified field default value when aggregator model instance is created the first time and uses the same for all instances. Because model instances are not saved(only values are extracted for raw query) [field pre_save](https://github.com/jazzband/django-model-utils/blob/4.0.0/model_utils/fields.py#L38) is never called and the same date is used for all instances until the model field object is destroyed and recreated. This PR sets the …
> MCKIN-30345: fix aggregator incorrect  modified date

- completion_aggregator/templates/chapter_completion_progress_bar.html
- completion_aggregator/templates/completion_progress_bar.html
- completion_aggregator/urls.py
- completion_aggregator/views.py
This PR adds new views that display progress bars for course-level and chapter-level progress.
This requires the changes from https://github.com/open-craft/edx-platform/pull/431 to be present.
**JIRA:** [SE-4473](https://tasks.opencraft.com/browse/SE-4473)
**Dependencies:** https://github.com/open-craft/edx-platform/pull/431 
1. Once you have a edx devstack setup with changes from https://github.com/open-craft/edx-platform/pull/431, install and enable completion tracking.
2. Pip install this django app and checkout the PR branch.
3. Make sure the feature flag "SHOW_PROGRESS_BAR" is set to True on your devstack.
4. Start a new course in LMS and check that the two progress bars are displayed and updated correctly.
**Reviewers:**
> [SE-4473] Add progress bar views

- completion_aggregator/views.py
**Description: **
This PR fixes an error where completion progress bar raises a TransactionManagementError 
if a user is not enrolled in a course.
The CompletionDetailView raises an 404 if it is unable to calculation
the completion details for a specific user/course
combination (eg. the user isn't enrolled in the course).
CompletionProgressBarView calls this view to determine the percentage
to show to a learner.
A 404 in the main transaction, causes it to be rolled back, hence any
further db calls will break with the error.
> django.db.transaction.TransactionManagementError: An error occurred
in the current transaction. You can't execute queries until the end of
the 'atomic' block.
The change in this commit wraps the offending code in another
transaction so that the inner transaction is …
> [SE-5145] Fix completion progress bar error when user not enrolled in course
